class SystemState:
    NOMINAL = "NOMINAL"
    MONITORING = "MONITORING"
    DEGRADED = "DEGRADED"
    ENGINE_ISOLATED = "ENGINE_ISOLATED"
    RELIGHT_PENDING = "RELIGHT_PENDING"
    RELIGHT_AUTHORIZED = "RELIGHT_AUTHORIZED"
    RELIGHT_ABORTED = "RELIGHT_ABORTED"
    STABILIZED = "STABILIZED"